#!/bin/sh  /etc/rc.common
#
# Copyright (c) 2018-2019, 2021 The Linux Foundation. All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

NSS_IPSEC_LOG_FILE=/tmp/.nss_ipsec_log
NSS_IPSEC_LOG_STR_ECM="ECM_Loaded"

ecm_load () {
	if [ ! -d /sys/module/ecm ]; then
		/etc/init.d/qca-nss-ecm start
		if [ -d /sys/module/ecm ]; then
			echo ${NSS_IPSEC_LOG_STR_ECM} >> ${NSS_IPSEC_LOG_FILE}
		fi
	fi
}

ecm_unload () {
	if [ -f /tmp/.nss_ipsec_log ]; then
		str=`grep ${NSS_IPSEC_LOG_STR_ECM} ${NSS_IPSEC_LOG_FILE}`
		if [[ $str == ${NSS_IPSEC_LOG_STR_ECM} ]]; then
			/etc/init.d/qca-nss-ecm stop
			`sed 's/${NSS_IPSEC_LOG_STR_ECM}/ /g' $NSS_IPSEC_LOG_FILE >  $NSS_IPSEC_LOG_FILE`
		fi
	fi
}

ecm_disable() {

	if [ ! -d /sys/module/ecm ]; then
		return;
	fi

	echo 1 > /sys/kernel/debug/ecm/front_end_ipv4_stop
	echo 1 > /sys/kernel/debug/ecm/front_end_ipv6_stop
	echo 1 > /sys/kernel/debug/ecm/ecm_db/defunct_all
	sleep 2
}

ecm_enable() {
	if [ ! -d /sys/module/ecm ]; then
		return;
	fi

	echo 0 > /sys/kernel/debug/ecm/ecm_db/defunct_all
	echo 0 > /sys/kernel/debug/ecm/front_end_ipv4_stop
	echo 0 > /sys/kernel/debug/ecm/front_end_ipv6_stop
}

start() {
	ecm_load

	local kernel_version=$(uname -r)

	# load all NETKEY modules first.
	for mod in xfrm_ipcomp ipcomp xfrm6_tunnel ipcomp6 xfrm6_mode_tunnel xfrm6_mode_beet xfrm6_mode_ro \
		xfrm6_mode_transport xfrm4_mode_transport xfrm4_mode_tunnel \
		xfrm4_tunnel xfrm4_mode_beet esp4 esp6 ah4 ah6 af_key
		do
			insmod $mod 2> /dev/null
		done

	# Now load the xfrm plugin
	insmod /lib/modules/${kernel_version}/qca-nss-ipsec-xfrm.ko
	if [ "$?" -gt 0 ]; then
		echo "Failed to load plugin. Please start ecm if not done already"
		ecm_enable
		return
	fi

	/etc/init.d/ipsec start
	sleep 2

	ecm_enable
}

stop() {
	ecm_disable

	#Shutdown Pluto first. Then only plugin can be removed.
	plutopid=/var/run/pluto/pluto.pid
	if [ -f $plutopid ]; then
		pid=`cat $plutopid`
		if [ ! -z "$pid" ]; then
			ipsec whack --shutdown | grep -v "002";
			if [ -s $plutopid ]; then
				echo "Attempt to shut Pluto down failed!  Trying kill:"
				kill $pid;
				sleep 5;
			fi
		fi
		rm -rf $plutopid
	fi
	sleep 2

	#Now we can remove the plugin
	retries=5
	while true
	do
		if [ -d /sys/module/qca_nss_ipsec_xfrm ]; then
			rmmod qca-nss-ipsec-xfrm
			if [ "$?" -gt 0 ]; then
				if [ $retries -gt 0 ] ;then
					retries=$((retries-1))
					echo "Plugin rmmod failed; re-try to rmmod again, after 1 sec"
					sleep 1
				else
					echo "Stop qca-nss-ipsec failed"
					exit
				fi
			else
				break
			fi
		else
			break
		fi
	done

	/etc/init.d/ipsec stop
	ecm_unload
}

restart() {
	stop
	start
}
